name: FTL Example

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
  
jobs:
  ftl_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        test_type: ['game-loop', 'xctest', 'robo', 'instrumentation']
    steps:
      - uses: actions/checkout@v3
      - id: ftl_test
        uses: FirebaseExtended/github-actions/firebase-test-lab@master
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          testapp_dir: ${{ github.workspace }}/testapps/${{ matrix.test_type }}
          test_type: ${{ matrix.test_type }}
      - run: echo '${{ steps.ftl_test.outputs.test_summary }}'
