name: FTL Tests [Experimental]

on:
  workflow_dispatch
  
jobs:
  ftl_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python_version: ['2.7', '3.10']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - id: ftl_test
        uses: FirebaseExtended/github-actions/firebase-test-lab@test/ftl-gha-secret
        with:
          arg_groups: demo_arg.yaml:robo-1
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: python read_test_result.py -r '${{ steps.ftl_test.outputs.test_summary }}'
        shell: bash
        if: ${{ !cancelled() }}
