name: FTL Example with YAML-input

on:
  workflow_dispatch
  
jobs:
  ftl_testing:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arg_groups: ["demo_arg.yaml:instrumentation","demo_arg.yaml:instrumentation;demo_arg.yaml:robo-1"]
    steps:
      - uses: actions/checkout@v3
      - id: ftl_test
        uses: FirebaseExtended/github-actions/firebase-test-lab@master
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          arg_groups: ${{ matrix.arg_groups }}
      - run: echo '${{ steps.ftl_test.outputs.test_summary }}'
