name: FTL Example

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
  
jobs:
  ftl_testing:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        test_type: ['game-loop', 'robo', 'instrumentation']
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - id: ftl_test
        uses: FirebaseExtended/github-actions/firebase-test-lab@master
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          testapp_dir: ${{ github.workspace }}/testapps/${{ matrix.test_type }}
          test_type: ${{ matrix.test_type }}
      - run: echo '${{ steps.ftl_test.outputs.test_summary }}'

  ftl_testing_with_arg:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arg_groups: ["demo_arg.yaml:instrumentation","demo_arg.yaml:instrumentation;demo_arg.yaml:robo-1"]
    steps:
      - uses: actions/checkout@v3
      - id: ftl_test
        uses: FirebaseExtended/github-actions/firebase-test-lab@master
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          arg_groups: ${{ matrix.arg_groups }}
      - run: echo '${{ steps.ftl_test.outputs.test_summary }}'

      
