name: ios-testing

on: workflow_dispatch

jobs:
  ftl-testing:
    # Don't run on private repo unless it is a PR.
    runs-on: macos-12
    env:
      bot_token_secret: ${{ secrets.GHASecretsGPGPassphrase1 }}
    outputs:
      matrix: ${{ steps.generate_matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get token
        run: |
          echo "123"
      - name: ftl-tests
          uses: FirebaseExtended/github-actions/firebase-test-lab@gl/firebase-test-lab
          with:
            testapp_dir: "${GITHUB_WORKSPACE}/scripts/firebase_test_lab/testapp"
            key_file: "${GITHUB_WORKSPACE}/games-project-key.json"
